### PR TITLE
On the assumption that "Jellyfish" is the correct spelling

### PR DESCRIPTION
**Pull request by comradekingu**
Ran into this conundrum somewhere else, hoping this matter can be settled.

### CODE REVIEW

**Comment by comradekingu** [comment]
@jamesturk Anything wrong with this?

**Comment by jamesturk** [comment]
Tox and Jellyfish are both lowercase :)

**Comment by comradekingu** [comment]
@jamesturk Not on the website it isn't. Jellyfish isn't "jellyfish" consistently on the landing page, and you just wrote it "Jellyfish"…

**Comment by jamesturk** [comment]
Not sure what website you're referring to, but I prefer to keep package
names lower case to match their import.  Thanks though!

**Comment by comradekingu** [comment]
@jamesturk That isn't the instance I changed though. Tox is "Tox" on https://tox.chat/
Regardless, the rest should be good, make changes as needed.

**Comment by jamesturk** [comment]
Ah different project! Tox chat vs tox testing :)

**Comment by comradekingu** [comment]
@jamesturk Ah, if you open this again I'll make that change, and then do "jellyfish" only, and the markup that is reserved for libraries so that it stands out.

**Pull request closed without merging**
