### PR TITLE
PEP8, flake8 and other minor cleanups

### PR DESCRIPTION
**Pull request by diego-plan9**
As hinted on a previous conversation, this pull request consists of a set of style changes in order to conform to PEP8, flake8 and other checks performed during Debian's packaging step. The bulk of the changes is a result of directly applying [autopep8](https://pypi.python.org/pypi/autopep8) at 32ed99b5bd999437c52b15057af7b4f927705531, plus some manual changes mainly geared towards splitting long lines (mostly on some rather complex `if` clauses).

Please let me know if this differs too much from your preferred style and conventions - I'd be more than happy to do another pass and adjust as needed!

### CODE REVIEW

**Comment by jamesturk** [comment]
I think something might be wrong in the setup, this is adding spaces around mathematical operators, which isn't really PEP8.  https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements

**Comment by diego-plan9** [comment]
Thanks for pointing it out, James. After some digging, it seems that using whitespaces around arithmetic operators *was* enforced on older PEP8 versions [(pre~2012)](https://hg.python.org/peps/rev/37af28ad2972), but currently it is not enforced and indeed left at the discretion of the developer.

The [pep8 tool docs](http://pep8.readthedocs.org/en/latest/intro.html#error-codes) also consider the "whitespace around arithmetic" recommendation a special case indeed:
> E226 (\*) 	missing whitespace around arithmetic operator
> ...
> (\*) In the default configuration, the checks E121, E123, E126, E133, **E226**, E241, E242 and E704 are ignored because they are not rules unanimously accepted, and PEP 8 does not enforce them

It seems that `autopep8` tried to fix the E226 errors by default - I'll revert those changes in order to keep your original style, as I fully understand the desire for keeping them as close to your original version as possible.

Don't hesitate on letting me know if you notice other discrepancies or personal style conventions that you'd like to keep!

**Comment by jamesturk** [comment]
Can we keep max-line-length=99 setting as it is in the tox.ini and exclude the Sphinx stuff (which isn't really part of the package)?

**Comment by diego-plan9** [comment]
Sure thing, I have reverted the changes that were geared towards fixing the E501 lines - my apologies for this pull request turning to be noisier than initially expected.

I'm wondering however if I could persuade you keep the Sphinx `docs/conf.py` changes, even if they are indeed not part of the package (although arguably part of the *distribution* due to the previous pull request), if only for having both `pep8` and `flake8` (with the line length and ignore E402, E226 flags) output no warnings when executed on the top level directory? It would be the only file left that triggers some warnings:
```bash
$ flake8 --statistics -q
./docs/conf.py
2       E121 continuation line under-indented for hanging indent
6       E122 continuation line missing indentation or outdented
45      E265 block comment should start with '# '
2       F401 'sys' imported but unused
```

**Comment by jamesturk** [comment]
OK it doesn't seem like it'll harm anything, thanks for working through this!

**Pull request merged**
