### PR TITLE
Add aarch64 CI and wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Closes https://github.com/jamesturk/jellyfish/issues/136

### CODE REVIEW

**Comment by jamesturk** [comment]
really appreciate this, I'll take some time soon to integrate this.  a bit of a busy week ahead of me so it might be a while, but I do appreciate it 👍

**Comment by layday** [comment]
Can we use cibuildwheel here to build wheels for Windows and macOS as well?  You can find a sample workflow at https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation.  I can do this in a separate PR if you'd prefer.

**Comment by odidev** [comment]
@layday, I pushed the changes to build Windows and macOS wheels as well via `cibuildwheel`. Can you please take a look? Thanks.

**Comment by layday** [comment]
LGTM :)

**Comment by jamesturk** [comment]
I’ll aim to take a look at this this week.  Thanks all!

James

**Comment by jamesturk** [comment]
Sorry, I had this PR and #135 linked in my head.  I'm not that familiar with the tools being used in this one, I'm curious if it is possible to add aarch support to the wheels that are now building as part of that PR's merge?

**Comment by layday** [comment]
#135 is building 'vanilla' Linux wheels which you cannot even upload to PyPI AFAIK on account of the fact that they are not guaranteed to work on any system other than the one they've been compiled on.  If you'd rather not use `cibuildwheel`, you can use the Docker images provided by the manylinux project directly, see https://github.com/pypa/manylinux#docker-images.

**Comment by jamesturk** [comment]
Gotcha, I'll need to do some reading to understand better where things like QEmu come into play

**Comment by ofek** [comment]
@odidev would you mind rebasing?

**Comment by odidev** [comment]
@jamesturk, could you please take a look at this PR? Thanks in advance.

**Comment by jamesturk** [comment]
thanks for this, it looks good to me

**Comment by odidev** [comment]
@jamesturk , I can see on PyPi, the latest release is done on Aug 05, 2021 but AArch64 wheels are missing. Could you please let me know the schedule to release AArch64 wheels?

**Comment by jamesturk** [comment]
If you have time/ motivation the github actions could use a second pass to get the arch working.

No ETA here yet but i’d take a look again when i have free time

**Pull request merged**
